version: "3"

services:
  subgame-network:
    image: subgame/network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subgame-network
    hostname: subgame-network
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    volumes:
      - .:/subgame
    command: bash -c "cargo build --release -p subgame-runtime"


networks:
  default:
    driver: bridge