version: "3"

services:
  subgame-network:
    image: subgame/network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subgame-network
    hostname: subgame-network
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    volumes:
      - .:/subgame
    command: bash -c "cargo build --release && ./target/release/subgame
      --base-path /subgame/storage
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --rpc-external
      --ws-external
      --rpc-cors=all
      --pruning=archive
      --bootnodes /dns4/subgamenode.subgame.org/tcp/30333/p2p/12D3KooWLTFnnpGPLQS1pyPoAA4PGgbsrUCRWASjbgMxd1ejVVT7"

networks:
  default:
    driver: bridge