version: "3"

services:
  subgame-network-validator:
    image: subgame/network-validator
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subgame-network-validator
    hostname: subgame-network-validator
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    volumes:
      - .:/subgame
    command: bash -c "./subgame.mainnet
      --chain main 
      --base-path /subgame/storage
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --rpc-cors=all
      --pruning=archive
      --rpc-external
      --ws-external
      --rpc-methods=Unsafe
      --validator
      --bootnodes /ip4/18.167.97.87/tcp/30333/p2p/12D3KooWNtQFxhJGfn3vKx9t8YTatxSNocsz73jZoxaoRSS8UCxJ"

networks:
  default:
    driver: bridge